# 仕様：https://qiita.com/yuta-ushijima/items/d3d98177e1b28f736f04
# docker-composeで使用するバージョンを定義
version: "3.9"
services:
  # postgresをサービスとして定義
  postgres:
    # Docker Imageはpostgres:12-alpine を使用
    image: postgres:12-alpine
    # コンテナの名前を指定
    container_name: postgres
    # 環境変数を設定
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    # データの永続化
    volumes:
      # postgresディレクトリを/var/lib/postgresql/dataにマウントする
      - postgres:/var/lib/postgresql/data
    # ポートの指定（HOST:CONTAINER）
    ports:
      - 5432:5432
# データの永続化
volumes:
  postgres:
